app = "flower-staging"
primary_region = "otp"

[build]
  image = "mher/flower:latest"

[experimental]
  allowed_public_ports = [5555]

[[services]]
  protocol = "tcp"
  internal_port = 5555

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = false

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 5555
    handlers = []

  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [services.basic_auth]
    username = "universal_auto_dev"
    password = "pass"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
