# Generated by Django 4.1.7 on 2023-03-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subscribeusers_driver_driver_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermanager',
            name='driver_id',
            field=models.ManyToManyField(blank=True, to='app.driver', verbose_name='Driver'),
        ),
    ]