# Generated by Django 4.1.7 on 2023-03-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_reportuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseOfCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_vehicle', models.CharField(max_length=255, verbose_name='Користувач автомобіля')),
                ('licence_plate', models.CharField(max_length=24, verbose_name='Номерний знак')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата використання авто')),
            ],
            options={
                'verbose_name': 'Користувачі автомобіля',
                'verbose_name_plural': 'Користувачі автомобілів',
            },
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_manager_id',
        ),
    ]
