# Generated by Django 4.1.7 on 2023-03-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_useofcars_remove_driver_driver_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useofcars',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Індетифікатор чата'),
        ),
    ]
