# Generated by Django 4.1.7 on 2023-04-01 08:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_useofcars_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status_job_application',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='car_documents',
            field=models.ImageField(blank=True, default='docs/default_car.jpg', upload_to='job/car', verbose_name='Фото техпаспорту'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='driver_license_back',
            field=models.ImageField(blank=True, upload_to='job/licenses/back', verbose_name='Тильна сторона посвідчення'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='driver_license_front',
            field=models.ImageField(blank=True, upload_to='job/licenses/front', verbose_name='Лицьова сторона посвідчення'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='insurance',
            field=models.ImageField(blank=True, default='docs/default_insurance.png', upload_to='job/insurance', verbose_name='Автоцивілка'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='insurance_expired',
            field=models.DateField(default=datetime.date(2023, 12, 15), verbose_name='Термін дії автоцивілки'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='license_expired',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Термін дії посвідчення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='password',
            field=models.CharField(default=1, max_length=12, verbose_name='Пароль Uklon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='photo',
            field=models.ImageField(blank=True, upload_to='job/photo', verbose_name='Фото водія'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_bolt',
            field=models.DateField(null=True, verbose_name='Опрацьована BOLT'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_uklon',
            field=models.DateField(null=True, verbose_name='Опрацьована Uklon'),
        ),
        migrations.AddField(
            model_name='newuklonfleet',
            name='token',
            field=models.CharField(default=None, null=True, max_length=40, verbose_name='Код автопарку'),
        ),
    ]
