# Generated by Django 4.1 on 2023-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_jobapplication_status_job_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Налаштування автопарка',
                'verbose_name_plural': 'Налаштування автопарків',
            },
        ),
    ]
