# Generated by Django 4.1 on 2023-04-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_useofcars_end_at_statuschange_rentinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportUser',
        ),
    ]
