# Generated by Django 4.1 on 2023-04-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_parkstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gps',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
