# Generated by Django 4.1 on 2023-04-14 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_comment_order_distance_google_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkstatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='parkstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
