# Generated by Django 4.1 on 2023-04-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_parkstatus_options_parkstatus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_delivery_price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
