# Generated by Django 4.1 on 2023-05-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_parksettings_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentinformation',
            options={'verbose_name_plural': 'Інформація по оренді'},
        ),
    ]
