# Generated by Django 4.1 on 2023-05-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_rentinformation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='ID в чаті'),
        ),
        migrations.AlterField(
            model_name='event',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Індетифікатор чата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='chat_id_client',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rentinformation',
            name='rent_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Орендована дистанція'),
        ),
        migrations.AlterField(
            model_name='useofcars',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Індетифікатор чата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Індетифікатор чата'),
        ),
    ]
