# Generated by Django 4.1 on 2023-05-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_service_boltservice_newuklonservice_uagpsservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_message_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_message_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
