# Generated by Django 4.1 on 2023-05-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_ninjafleet_alter_boltpaymentsorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjapaymentsorder',
            name='total_amount_cach',
        ),
        migrations.AddField(
            model_name='ninjapaymentsorder',
            name='total_amount_cash',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ninjapaymentsorder',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ninjapaymentsorder',
            name='total_amount_on_card',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ninjapaymentsorder',
            name='total_rides',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='chat_id_client',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_message_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='distance_gps',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_message_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_the_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
