# Generated by Django 4.1 on 2023-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_park_partner_ubertrips_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car_delivery_price',
            field=models.IntegerField(default=0, verbose_name='Сума за подачу автомобіля'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='Загальна сума'),
        ),
    ]
