# Generated by Django 4.1 on 2023-06-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_order_car_delivery_price_alter_order_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_report', models.DateTimeField(verbose_name='Звіт з')),
                ('end_report', models.DateTimeField(verbose_name='Звіт по')),
                ('driver', models.CharField(max_length=25, null=True, verbose_name='Водій авто')),
                ('mileage', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Пробіг, км')),
                ('efficiency', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Ефективність, грн/км')),
            ],
            options={
                'verbose_name': 'Ефективність автомобіля',
                'verbose_name_plural': 'Ефективність автомобілів',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.RemoveField(
            model_name='drivermanager',
            name='role',
        ),
        migrations.RemoveField(
            model_name='fleets_drivers_vehicles_rate',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='fleets_drivers_vehicles_rate',
            name='withdraw_money',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='role',
        ),
        migrations.RemoveField(
            model_name='servicestationmanager',
            name='role',
        ),
        migrations.RemoveField(
            model_name='supportmanager',
            name='role',
        ),
        migrations.AddField(
            model_name='driver',
            name='plan',
            field=models.IntegerField(default=12000, verbose_name='План водія'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3, verbose_name='Відсоток водія'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rental',
            field=models.IntegerField(default=6000, verbose_name='Вартість прокату'),
        ),
        migrations.AddField(
            model_name='driver',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schema',
                                    verbose_name='Схема роботи'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager'), ('OWNER', 'Owner')], default='CLIENT', max_length=25),
        ),
    ]
