# Generated by Django 4.1 on 2023-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_park_options_remove_vehicle_driver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='park',
            options={'verbose_name': 'Автопарк партнера', 'verbose_name_plural': 'Автопарки партнерів'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_id',
            field=models.IntegerField(default=0),
        ),
    ]
