# Generated by Django 4.1 on 2023-07-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_park_options_vehicle_gps_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Інформаційна панель автопарку',
                'verbose_name_plural': 'Інформаційна панель автопарку',
            },
        ),
        migrations.AddField(
            model_name='carefficiency',
            name='total_kasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всього каса'),
        ),
        migrations.AddField(
            model_name='carefficiency',
            name='vehicle',
            field=models.CharField(max_length=255, null=True, verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='boltpaymentsorder',
            name='driver_full_name',
            field=models.CharField(max_length=50, verbose_name='ПІ водія'),
        ),
        migrations.AlterField(
            model_name='carefficiency',
            name='driver',
            field=models.CharField(max_length=50, null=True, verbose_name='Водій авто'),
        ),
        migrations.AlterField(
            model_name='uberpaymentsorder',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Імя водія'),
        ),
        migrations.AlterField(
            model_name='uberpaymentsorder',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище водія'),
        ),
    ]
