# Generated by Django 4.1 on 2023-07-17 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_payments_summaryreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parksettings',
            name='park',
        ),
        migrations.AddField(
            model_name='parksettings',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Автопарк'),
        ),
        migrations.DeleteModel(
            name='Park',
        ),
    ]
