# Generated by Django 4.1 on 2023-07-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_ubersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='useofcars',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
    ]
