# Generated by Django 4.1 on 2023-08-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_useofcars_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Відпочинок і лікування', 'verbose_name_plural': 'Відпочинки і лікування'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='status_event',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час події'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='coord_time',
            field=models.DateTimeField(null=True, verbose_name='Час отримання координат'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, null=True, verbose_name='Довгота'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='Номер документа'),
        ),
    ]
