# Generated by Django 4.1 on 2023-08-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_event_options_remove_event_status_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.CharField(max_length=255, null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.CreateModel(
            name='FleetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, verbose_name='Ідентифікатор замовлення')),
                ('fleet', models.CharField(max_length=20, verbose_name='Агрегатор замовлення')),
                ('driver', models.CharField(max_length=255, verbose_name='Водій')),
                ('from_address', models.CharField(max_length=255, verbose_name='Місце посадки')),
                ('destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце висадки')),
                ('accepted_time', models.DateTimeField(blank=True, null=True, verbose_name='Час прийняття замовленя')),
                ('finish_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Час завершення замовлення')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус замовлення')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Стороннє замовлення',
                'verbose_name_plural': 'Сторонні замовлення',
            },
        ),
    ]
