# Generated by Django 4.1 on 2023-08-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_order_info_fleetorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTelegramPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_payment_charge_id', models.CharField(max_length=50, verbose_name='Унікальний індитифікатор оплати в провайдері')),
                ('telegram_payment_charge_id', models.CharField(max_length=50, verbose_name='Унікальний індитифікатор оплати в телеграмі')),
                ('currency', models.CharField(max_length=24, verbose_name='Валюта')),
                ('total_amount', models.PositiveIntegerField(verbose_name='Сума оплати')),
            ],
            options={
                'verbose_name': 'Звіт про оплату в телеграмі',
                'verbose_name_plural': 'Звіти про оплату в телеграмі',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='report_tg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.reporttelegrampayments', verbose_name='Звіти про оплату в телеграмі'),
        ),
    ]
