# Generated by Django 4.1 on 2023-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_carefficiency_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentinformation',
            name='road_time',
        ),
        migrations.AddField(
            model_name='driverefficiency',
            name='online_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Час онлайн'),
        ),
        migrations.AddField(
            model_name='driverefficiency',
            name='road_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Час в дорозі'),
        ),
        migrations.DeleteModel(
            name='ParkStatus',
        ),
    ]
