# Generated by Django 4.1 on 2023-08-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_rentinformation_road_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Заробіток авто'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='currency_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курс валюти при покупці(НБУ)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='investor',
            field=models.BooleanField(default=False, verbose_name='Машина інвестора'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна покупки'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='сurrency',
            field=models.CharField(choices=[('UAH', 'Гривня'), ('USD', 'Долар'), ('EUR', 'Євро')], default='UAH', max_length=4, verbose_name='Валюта покупки'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='сurrency_back',
            field=models.CharField(choices=[('UAH', 'Гривня'), ('USD', 'Долар'), ('EUR', 'Євро')], default='UAH', max_length=4, verbose_name='Валюта повернення коштів'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_status',
            field=models.CharField(default='Не працюю', max_length=35, verbose_name='Статус водія'),
        ),
        migrations.CreateModel(
            name='TransactionsConversantion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_before_transaction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума до транзакції')),
                ('сurrency', models.CharField(max_length=4, verbose_name='Валюта покупки')),
                ('currency_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курс валюти')),
                ('sum_after_transaction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума після транзакції')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle', verbose_name='Машина')),
            ],
        ),
    ]
