# Generated by Django 4.1 on 2023-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_vehicle_car_earnings_vehicle_currency_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='investor_percentage',
            field=models.DecimalField(decimal_places=2, default=0.35, max_digits=10, verbose_name='Відсоток інвестора'),
        ),
    ]
