# Generated by Django 4.1 on 2023-09-04 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_transactionsconversantion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_message_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver_message_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_hours',
            field=models.IntegerField(null=True, verbose_name='Годин Сплачено'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_order',
            field=models.CharField(default='Звичайне замовлення', max_length=100, verbose_name='Тип замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Картка', max_length=70, verbose_name='Спосіб оплати'),
        ),
        migrations.CreateModel(
            name='DriverReshuffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_event_id', models.CharField(max_length=100)),
                ('swap_time', models.DateTimeField(verbose_name='Час початку/завершення зміни')),
                ('driver_finish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_finish', to='app.driver', verbose_name='Водій, що віддає авто')),
                ('driver_start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_start', to='app.driver', verbose_name='Водій, що приймає авто')),
                ('swap_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehicle', verbose_name='Автомобіль')),
            ],
        ),
    ]
