# Generated by Django 4.1 on 2023-09-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_order_client_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='login',
            field=models.CharField(default=1, max_length=255, verbose_name='Логін'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default=1, max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Електрона пошта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(default=1, max_length=255, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Прізвище'),
            preserve_default=False,
        ),
    ]
