# Generated by Django 4.1 on 2023-09-12 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_manager_login_manager_password_alter_manager_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=10, verbose_name='Індетифікатор чата')),
                ('duty', models.IntegerField(default=0, verbose_name='Борг>')),
            ],
            options={
                'verbose_name': 'Банк боргів',
                'verbose_name_plural': 'Банк боргів',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='report_tg',
        ),
        migrations.AddField(
            model_name='driver',
            name='worked',
            field=models.BooleanField(default=True, verbose_name='Працює'),
        ),
        migrations.AddField(
            model_name='reporttelegrampayments',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Замовлення'),
        ),
    ]
