# Generated by Django 4.1 on 2023-09-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_driver_fleet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleets_drivers_vehicles_rate',
            options={'verbose_name': 'Водій в агрегаторах', 'verbose_name_plural': 'Водії в агрегаторах'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='support_manager_id',
        ),
        migrations.AlterField(
            model_name='carefficiency',
            name='total_kasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Каса'),
        ),
        migrations.AlterField(
            model_name='carefficiency',
            name='total_spendings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Витрати'),
        ),
        migrations.AlterField(
            model_name='driverefficiency',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.driver', verbose_name='Водій'),
        ),
        migrations.AlterField(
            model_name='driverefficiency',
            name='total_kasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Каса'),
        ),
        migrations.AlterField(
            model_name='driverefficiency',
            name='total_orders',
            field=models.IntegerField(default=0, verbose_name='Замовлень за день'),
        ),
        migrations.AlterField(
            model_name='fleets_drivers_vehicles_rate',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fleet', verbose_name='Агрегатор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gps_imei',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin_code',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
