# Generated by Django 4.1 on 2023-09-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_fleets_drivers_vehicles_rate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Індетифікатор чата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електрона пошта'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Додано автомобіль'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість автомобіля'),
        ),
    ]
