# Generated by Django 4.1 on 2023-09-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_carefficiency_clean_kasa_alter_vehicle_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('category', models.CharField(choices=[('FUEL', 'Паливо'), ('SERVICE', 'Сервісне обслуговування'), ('REPAIR', 'Ремонт'), ('WASHING', 'Мийка'), ('OTHER', 'Інше')], max_length=255, verbose_name='Категорія витрат')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='spending/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle', verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Витрата',
                'verbose_name_plural': 'Витрати',
            },
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.RemoveField(
            model_name='vehiclespendings',
            name='vehicle',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клієнта', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водія', 'verbose_name_plural': 'Водії'},
        ),
        migrations.AlterModelOptions(
            name='fleets_drivers_vehicles_rate',
            options={'verbose_name': 'Водія в агрегаторах', 'verbose_name_plural': 'Водії в агрегаторах'},
        ),
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name': 'Інвестора', 'verbose_name_plural': 'Інвестори'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Менеджера', 'verbose_name_plural': 'Менеджери'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Власника', 'verbose_name_plural': 'Власники'},
        ),
        migrations.AlterModelOptions(
            name='rentinformation',
            options={'verbose_name': 'Інформацію по оренді', 'verbose_name_plural': 'Інформація по орендах'},
        ),
        migrations.AlterModelOptions(
            name='servicestationmanager',
            options={'verbose_name': 'Менеджера сервісного центра', 'verbose_name_plural': 'Менеджери сервісних центрів'},
        ),
        migrations.AlterModelOptions(
            name='subscribeusers',
            options={'verbose_name': 'Підписника', 'verbose_name_plural': 'Підписники'},
        ),
        migrations.AlterModelOptions(
            name='supportmanager',
            options={'verbose_name': 'Менеджера служби підтримки', 'verbose_name_plural': 'Менеджери служби підтримки'},
        ),
        migrations.AlterModelOptions(
            name='transactionsconversantion',
            options={'verbose_name': 'Транзакцію', 'verbose_name_plural': 'Транзакції'},
        ),
        migrations.AlterModelOptions(
            name='useofcars',
            options={'verbose_name': 'Користувача автомобіля', 'verbose_name_plural': 'Користувачі автомобілів'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувача', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AddField(
            model_name='manager',
            name='calendar',
            field=models.CharField(default=123, max_length=255, verbose_name='Календар змін водіїв'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='calendar',
            field=models.CharField(default=123, max_length=255, verbose_name='Календар змін водіїв'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ідентифікатор чата'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ідентифікатор чата'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ідентифікатор чата'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ідентифікатор чата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ідентифікатор чата'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='VehicleSpendings',
        ),
    ]
