# Generated by Django 4.1 on 2023-09-27 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def update_vehicle_foreign_keys(apps, schema_editor):
    Vehicle = apps.get_model('app', 'Vehicle')
    CarEfficiency = apps.get_model('app', 'CarEfficiency')

    for car_efficiency in CarEfficiency.objects.all():
        try:
            vehicle = Vehicle.objects.get(licence_plate=car_efficiency.licence_plate)
            car_efficiency.vehicle = vehicle
            car_efficiency.save()
        except Vehicle.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_vehiclespending_delete_dashboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_before_transaction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума в гривні')),
                ('currency', models.CharField(max_length=4, verbose_name='Валюта покупки')),
                ('currency_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курс валюти')),
                ('sum_after_transaction', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума у валюті')),
            ],
            options={
                'verbose_name': 'Виплату інвестору',
                'verbose_name_plural': 'Виплати інвестору',
            },
        ),
        migrations.AlterModelOptions(
            name='vehiclespending',
            options={'verbose_name': 'Витрату', 'verbose_name_plural': 'Витрати'},
        ),
        migrations.RenameField(
            model_name='carefficiency',
            old_name='total_spendings',
            new_name='total_spending',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='сurrency',
            new_name='currency',
        ),
        migrations.AddField(
            model_name='carefficiency',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle',
                                    verbose_name='Автомобіль'),
        ),
        migrations.RunPython(update_vehicle_foreign_keys),
        migrations.RemoveField(
            model_name='carefficiency',
            name='licence_plate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='сurrency_back',
        ),

        migrations.AddField(
            model_name='investor',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254, verbose_name='Електронна пошта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Прізвище'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='investor',
            name='password',
            field=models.CharField(default=123456, max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chat_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Група автомобіля телеграм'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='currency_back',
            field=models.CharField(choices=[('UAH', 'Гривня'), ('USD', 'Долар'), ('EUR', 'Євро')], default='USD', max_length=4, verbose_name='Валюта повернення коштів'),
        ),
        migrations.AlterField(
            model_name='carefficiency',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='fleets_drivers_vehicles_rate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='newuklonpaymentsorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='report_of_driver_debt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='subscribeusers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='summaryreport',
            name='total_amount_without_fee',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Чистий дохід'),
        ),
        migrations.AlterField(
            model_name='summaryreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='uberpaymentsorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='currency_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курс валюти при покупці (НБУ)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='licence_plate',
            field=models.CharField(db_index=True, max_length=24, unique=True, verbose_name='Номерний знак'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.DeleteModel(
            name='TransactionsConversantion',
        ),
        migrations.AddField(
            model_name='transactionsconversation',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.investor', verbose_name='Інвестор'),
        ),
        migrations.AddField(
            model_name='transactionsconversation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle', verbose_name='Автомобіль'),
        ),
    ]
