# Generated by Django 4.1 on 2023-10-10 07:59

from django.db import migrations, models
import django.db.models.deletion


def migrate_data(apps, schema_editor):
    FleetOrder = apps.get_model('app', 'FleetOrder')
    Driver = apps.get_model('app', 'Driver')

    for obj in FleetOrder.objects.all():
        name, second_name = obj.driver.split()
        driver, _ = Driver.objects.get_or_create(name=name, second_name=second_name)
        obj.driver = driver.pk
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_partner_contacts_alter_driver_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetorder',
            name='payment',
            field=models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка')], max_length=25, null=True, verbose_name='Тип оплати'),
        ),
        migrations.AddField(
            model_name='fleetorder',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Вартість'),
        ),
        migrations.AddField(
            model_name='fleetorder',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehicle', verbose_name='Автомобіль'),
        ),
        migrations.RunPython(migrate_data),
        migrations.AlterField(
            model_name='fleetorder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver', verbose_name='Водій'),
        ),
    ]
