# Generated by Django 4.1 on 2023-10-18 09:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_carefficiency_clean_kasa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverreshuffle',
            name='driver_finish',
        ),
        migrations.AddField(
            model_name='driverefficiency',
            name='vehicles',
            field=models.ManyToManyField(db_index=True, to='app.vehicle', verbose_name='Автомобілі'),
        ),
        migrations.AddField(
            model_name='driverreshuffle',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час завершення зміни'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverreshuffle',
            name='driver_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.driver', verbose_name='Водій'),
        ),
        migrations.AlterField(
            model_name='driverreshuffle',
            name='swap_time',
            field=models.DateTimeField(verbose_name='Час початку зміни'),
        ),
    ]
