# Generated by Django 4.1 on 2023-10-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_remove_driverreshuffle_driver_finish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverEffVehicleKasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='salary_calculation',
        ),
        migrations.AddField(
            model_name='carefficiency',
            name='drivers',
            field=models.ManyToManyField(db_index=True, through='app.DriverEffVehicleKasa', to='app.driver', verbose_name='Водії'),
        ),
        migrations.AddField(
            model_name='schema',
            name='salary_calculation',
            field=models.CharField(choices=[('WEEK', 'Тижневий'), ('DAY', 'Денний')], default='WEEK', max_length=25, verbose_name='Період розрахунку зарплати'),
        ),
        migrations.AddField(
            model_name='schema',
            name='shift_period',
            field=models.IntegerField(choices=[('ONE', 'Один день'), ('TWO', 'Два дні'), ('THREE', 'Три дні')], null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='shift_time',
            field=models.TimeField(null=True, verbose_name='Час проведення розрахунку'),
        ),
        migrations.AddField(
            model_name='drivereffvehiclekasa',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
        ),
        migrations.AddField(
            model_name='drivereffvehiclekasa',
            name='efficiency_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carefficiency'),
        ),
    ]
