# Generated by Django 4.1 on 2023-10-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_drivereffvehiclekasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeusers',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribeusers',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, verbose_name='Номер телефону'),
            preserve_default=False,
        ),
    ]
