# Generated by Django 4.1 on 2023-11-13 14:09

from django.db import migrations, models
import django.db.models.deletion
import selenium_ninja.synchronizer


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_subscribeusers_name_subscribeusers_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoltFleet',
            new_name='BoltRequest',
        ),
        migrations.CreateModel(
            name='GPSNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('gps_id', models.IntegerField(default=0)),
                ('partner',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner',
                                   verbose_name='Партнер')),
            ],
        ),
        migrations.CreateModel(
            name='UaGpsSynchronizer',
            fields=[
                ('fleet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.fleet')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.fleet',),
        ),
        migrations.RenameModel(
            old_name='UberFleet',
            new_name='UberRequest',
        ),
        migrations.RenameModel(
            old_name='NewUklonFleet',
            new_name='UklonRequest',
        ),
        migrations.RemoveField(
            model_name='boltpaymentsorder',
            name='partner',
        ),
        migrations.DeleteModel(
            name='BoltTransactions',
        ),
        migrations.DeleteModel(
            name='FileNameProcessed',
        ),
        migrations.RemoveField(
            model_name='newuklonpaymentsorder',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='uberpaymentsorder',
            name='partner',
        ),
        migrations.DeleteModel(
            name='UberTransactions',
        ),
        migrations.DeleteModel(
            name='WeeklyReportFile',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='gps_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers', verbose_name='Фото водія'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнери'),
        ),
        migrations.AddField(
            model_name='partner',
            name='gps_url',
            field=models.URLField(null=True, verbose_name='Сторінка логіну Gps'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(null=True, verbose_name='Дата початку роботи'),
        ),
        migrations.DeleteModel(
            name='BoltPaymentsOrder',
        ),
        migrations.DeleteModel(
            name='NewUklonPaymentsOrder',
        ),
        migrations.DeleteModel(
            name='UberPaymentsOrder',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gpsnumber', verbose_name='Назва авто в Gps'),
        ),
        migrations.RemoveField(
            model_name='uklonrequest',
            name='token',
        ),
        migrations.AddField(
            model_name='boltrequest',
            name='base_url',
            field=models.URLField(default='https://fleetownerportal.live.boltsvc.net/fleetOwnerPortal/'),
        ),
        migrations.AddField(
            model_name='uberrequest',
            name='base_url',
            field=models.URLField(default='https://supplier.uber.com/graphql'),
        ),
        migrations.AddField(
            model_name='uklonrequest',
            name='base_url',
            field=models.URLField(default='https://fleets.uklon.com.ua/api/'),
        ),
    ]
