# Generated by Django 4.1 on 2023-12-20 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def replace_driver_payments(apps, schema_editor):
    Payments = apps.get_model('app', 'DriverPayments')
    Earnings = apps.get_model('app', 'Earnings')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    for payment in Payments.objects.all():
        earning = Earnings.objects.create(report_from=payment.report_from,
                                          report_to=payment.report_to,
                                          earning=payment.salary,
                                          partner=payment.partner)
        content_type = ContentType.objects.get_for_model(payment)
        payment.earnings_ptr = earning
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0067_remove_investor_email_remove_investor_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateField(verbose_name='Дохід з')),
                ('report_to', models.DateField(verbose_name='Дохід по')),
                ('earning', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума доходу')),
                ('status', models.CharField(
                    choices=[('checking', 'Перевіряється'), ('pending', 'Очікується'), ('completed', 'Виплачений'),
                             ('failed', 'Не сплачений')], default='checking', max_length=20)),
                ('partner',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner',
                                   verbose_name='Партнер')),
                ('polymorphic_ctype',
                 models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='polymorphic_%(app_label)s.%(class)s_set+',
                                   to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='VehicleRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField(verbose_name='Звіт з')),
                ('report_to', models.DateTimeField(verbose_name='Звіт по')),
                ('rent_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True,
                                                      verbose_name='Орендована дистанція')),
            ],
        ),
        migrations.CreateModel(
            name='FiredDriver',
            fields=[
            ],
            options={
                'verbose_name': 'Звільненого водія',
                'verbose_name_plural': 'Звільнені водії',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.driver',),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='worked',
        ),
        migrations.AddField(
            model_name='fleetorder',
            name='road_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Час в дорозі'),
        ),
        migrations.AddField(
            model_name='fleetorder',
            name='tips',
            field=models.IntegerField(null=True, verbose_name='Чайові'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True,
                                    validators=[django.core.validators.EmailValidator()],
                                    verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True,
                                   validators=[django.core.validators.MaxLengthValidator(255)], verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True,
                                   validators=[django.core.validators.RegexValidator('^(\\+380|380|80|0)+\\d{9}$')],
                                   verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True,
                                   validators=[django.core.validators.MaxLengthValidator(255)],
                                   verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gps_imei',
            field=models.CharField(blank=True, default='', max_length=50,
                                   validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='licence_plate',
            field=models.CharField(max_length=24, unique=True,
                                   validators=[django.core.validators.MaxLengthValidator(24)],
                                   verbose_name='Номерний знак'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)],
                                   verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin_code',
            field=models.CharField(blank=True, max_length=17,
                                   validators=[django.core.validators.MaxLengthValidator(17)]),
        ),
        migrations.CreateModel(
            name='InvestorPayments',
            fields=[
                ('earnings_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='app.earnings')),
                ('currency', models.CharField(max_length=4, verbose_name='Валюта покупки')),
                ('currency_rate',
                 models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курс валюти')),
                ('sum_after_transaction',
                 models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума у валюті')),
                ('investor',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.investor',
                                   verbose_name='Інвестор')),
                ('vehicle',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle',
                                   verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Виплату інвестору',
                'verbose_name_plural': 'Виплати інвестору',
            },
            bases=('app.earnings',),
        ),
        migrations.CreateModel(
            name='PartnerEarnings',
            fields=[
                ('earnings_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='app.earnings')),
                ('driver',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver',
                                   verbose_name='Водій')),
                ('vehicle',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle',
                                   verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Дохід',
                'verbose_name_plural': 'Доходи',
            },
            bases=('app.earnings',),
        ),
        migrations.DeleteModel(
            name='TransactionsConversation',
        ),
        migrations.AddField(
            model_name='vehiclerent',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.driver',
                                    verbose_name='Водій'),
        ),
        migrations.AddField(
            model_name='vehiclerent',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner',
                                    verbose_name='Партнери'),
        ),
        migrations.AddField(
            model_name='vehiclerent',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehicle',
                                    verbose_name='Автомобіль'),
        ),
        migrations.AddField(
            model_name='driverpayments',
            name='earnings_ptr',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=False, serialize=False, to='app.earnings'),
            preserve_default=False,
        ),
        migrations.RunPython(replace_driver_payments),
    ]
