# Generated by Django 4.1 on 2023-12-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_earnings_vehiclerent_fireddriver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverpayments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driverpayments',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='driverpayments',
            name='report_from',
        ),
        migrations.RemoveField(
            model_name='driverpayments',
            name='report_to',
        ),
        migrations.RemoveField(
            model_name='driverpayments',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='driverpayments',
            name='salary',
        ),
        migrations.AlterField(
            model_name='driverpayments',
            name='earnings_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.earnings'),
        ),
    ]
