# Generated by Django 4.1 on 2023-12-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0069_remove_driverpayments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, default='drivers/default-driver.png', null=True, upload_to='drivers', verbose_name='Фото водія'),
        ),
        migrations.CreateModel(
            name='PenaltyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Опис')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver', verbose_name='Водій')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Штраф/Бонус',
                'verbose_name_plural': 'Штрафи та Бонуси',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('penaltybonus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.penaltybonus')),
                ('driver_payments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driverpayments', verbose_name='Виплата водію')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.penaltybonus',),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('penaltybonus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.penaltybonus')),
                ('driver_payments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driverpayments', verbose_name='Виплата водію')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.penaltybonus',),
        ),
    ]
