# Generated by Django 4.1 on 2023-12-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_driver_photo_penaltybonus_penalty_bonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customreport',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='reporttelegrampayments',
            name='telegram_payment_charge_id',
            field=models.CharField(max_length=50, verbose_name='Ідентифікатор оплати в телеграмі'),
        ),
        migrations.AlterField(
            model_name='useofcars',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ідентифікатор чата'),
        ),
        migrations.AlterField(
            model_name='userbank',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ідентифікатор чата'),
        ),
        migrations.AlterField(
            model_name='vehiclerent',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner',
                                    verbose_name='Партнер'),
        ),
        migrations.CreateModel(
            name='DriverReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField(verbose_name='Звіт з')),
                ('report_to', models.DateTimeField(null=True, verbose_name='Звіт по')),
                ('total_amount_without_fee',
                 models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Чистий дохід')),
                ('total_amount_cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Готівкою')),
                ('total_amount_on_card',
                 models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='На картку')),
                ('total_amount',
                 models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Загальна сума')),
                ('total_rides', models.PositiveIntegerField(null=True, verbose_name='Кількість поїздок')),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=10, null=True,
                                                       verbose_name='Пробіг під замовленням')),
                ('tips', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Чайові')),
                ('bonuses', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Бонуси')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Комісія')),
                ('fares', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Штрафи')),
                ('cancels',
                 models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Плата за скасування')),
                ('compensations',
                 models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Компенсації')),
                ('refunds',
                 models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Повернення коштів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver',
                                             verbose_name='Водій')),
                ('partner',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner',
                                   verbose_name='Партнер')),
                ('polymorphic_ctype',
                 models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='polymorphic_%(app_label)s.%(class)s_set+',
                                   to='contenttypes.contenttype')),
                ('vehicle',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle',
                                   verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Звіт водія',
                'verbose_name_plural': 'Зведені звіти',
            },
        ),
        migrations.AlterUniqueTogether(
            name='payments',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='phone_number',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='driver_id',
            new_name='rider_id',
        ),
        migrations.RenameField(
            model_name='customreport',
            old_name='driver_id',
            new_name='rider_id',
        ),
        migrations.AddField(
            model_name='customreport',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fleet', verbose_name='Агрегатор'),
        ),
        migrations.AddField(
            model_name='payments',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fleet',
                                    verbose_name='Агрегатор'),
        ),
        migrations.AddField(
            model_name='payments',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver',
                                    verbose_name='Водій', related_name='payment_driver'),
        ),
        migrations.AddField(
            model_name='customreport',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver',
                                    verbose_name='Водій'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='driverschemarate',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='fleetorder',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час прийняття замовлення'),
        ),
        migrations.AlterField(
            model_name='fleetsdriversvehiclesrate',
            name='driver_external_id',
            field=models.CharField(max_length=255, verbose_name='Унікальний ідентифікатор по автопарку'),
        ),
        migrations.AlterField(
            model_name='fleetsdriversvehiclesrate',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investors_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='managers_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час прийняття замовлення'),
        ),
        migrations.AlterField(
            model_name='rentinformation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='reporttelegrampayments',
            name='provider_payment_charge_id',
            field=models.CharField(max_length=50, verbose_name='Ідентифікатор оплати в провайдері'),
        ),
        migrations.AddField(
            model_name='customreport',
            name='driverreport_ptr',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=False, serialize=False, to='app.driverreport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='driverreport_ptr',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=False, serialize=False, to='app.driverreport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='driverreport_ptr',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=False, serialize=False, to='app.driverreport'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('driverreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.driverreport')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fleet', verbose_name='Агрегатор')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.driverreport',),
        ),
    ]
