# Generated by Django 4.1 on 2024-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_remove_customreport_bonuses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverefficiency',
            name='online_time',
        ),
        migrations.AddField(
            model_name='driverpayments',
            name='payment_type',
            field=models.CharField(choices=[('WEEK', 'Тижневий'), ('DAY', 'Денний')], default='WEEK', max_length=20, verbose_name='Тип платежу'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='report_from',
            field=models.DateTimeField(verbose_name='Дохід з'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='report_to',
            field=models.DateTimeField(verbose_name='Дохід по'),
        ),
    ]
