# Generated by Django 4.1 on 2024-01-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_remove_driverefficiency_online_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='driver_payments',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='driver_payments',
        ),
        migrations.AddField(
            model_name='penaltybonus',
            name='driver_payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driverpayments', verbose_name='Виплата водію'),
        ),
    ]
