# Generated by Django 4.1 on 2024-01-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_remove_bonus_driver_payments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customreport',
            old_name='vendor',
            new_name='fleet',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='vendor',
            new_name='fleet',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='vendor',
            new_name='fleet',
        ),
        migrations.RenameField(
            model_name='weeklyreport',
            old_name='vendor',
            new_name='fleet',
        ),
    ]
