# Generated by Django 4.1 on 2024-01-03 11:18

from django.db import migrations, models
import django.db.models.deletion


def replace_driver_efficiency(apps, schema_editor):
    DriverEfficiency = apps.get_model('app', 'DriverEfficiency')
    DriverEfficiencyPolymorphic = apps.get_model('app', 'DriverEfficiencyPolymorphic')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    for driver_efficiency in DriverEfficiency.objects.all():
        content_type = ContentType.objects.get_for_model(driver_efficiency)
        driver_efficiency_polymorphic = DriverEfficiencyPolymorphic.objects.create(
            report_from=driver_efficiency.report_from,
            report_to=driver_efficiency.report_to,
            total_kasa=driver_efficiency.total_kasa,
            total_orders=driver_efficiency.total_orders,
            accept_percent=driver_efficiency.accept_percent,
            average_price=driver_efficiency.average_price,
            mileage=driver_efficiency.mileage,
            efficiency=driver_efficiency.efficiency,
            road_time=driver_efficiency.road_time,
            driver=driver_efficiency.driver,
            partner=driver_efficiency.partner,
            polymorphic_ctype=content_type
        )
        driver_efficiency_polymorphic.vehicles.set(driver_efficiency.vehicles.all()),
        driver_efficiency_polymorphic.save()
        driver_efficiency.driverefficiencypolymorphic_ptr = driver_efficiency_polymorphic
        driver_efficiency.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0076_rename_vendor_customreport_fleet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverEfficiencyPolymorphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField(verbose_name='Звіт з')),
                ('report_to', models.DateTimeField(null=True, verbose_name='Звіт по')),
                ('total_kasa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Каса')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Замовлень за день')),
                ('accept_percent', models.IntegerField(default=0, verbose_name='Відсоток прийнятих замовлень')),
                ('average_price',
                 models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Середній чек, грн')),
                ('mileage', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Пробіг, км')),
                ('efficiency',
                 models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ефективність, грн/км')),
                ('road_time', models.DurationField(blank=True, null=True, verbose_name='Час в дорозі')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.driver',
                                             verbose_name='Водій')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner',
                                              verbose_name='Партнер')),
                ('polymorphic_ctype',
                 models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='polymorphic_%(app_label)s.%(class)s_set+',
                                   to='contenttypes.contenttype')),
                ('vehicles', models.ManyToManyField(db_index=True, to='app.vehicle', verbose_name='Автомобілі')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='driverefficiency',
            options={'verbose_name': 'Ефективність водія',
                     'verbose_name_plural': 'Ефективність водіїв'},
        ),
        migrations.CreateModel(
            name='DriverEfficiencyFleet',
            fields=[
                ('driverefficiencypolymorphic_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='app.driverefficiencypolymorphic')),
                ('fleet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fleet',
                                            verbose_name='Агрегатор')),
            ],
            options={
                'verbose_name': 'Ефективність водія в агрегаторах',
                'verbose_name_plural': 'Ефективність водіїв в агрегаторах',
            },
            bases=('app.driverefficiencypolymorphic',),
        ),
        migrations.AddField(
            model_name='driverefficiency',
            name='driverefficiencypolymorphic_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                       null=True, primary_key=False, serialize=False,
                                       to='app.driverefficiencypolymorphic'),
            preserve_default=False,
        ),
        migrations.RunPython(replace_driver_efficiency),
    ]
