# Generated by Django 4.1 on 2024-01-26 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_alter_dailyreport_options_alter_driverreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverefficiencypolymorphic',
            name='total_orders_rejected',
            field=models.IntegerField(default=0, verbose_name='Відмовлено в замовленнях'),
        ),
        migrations.AddField(
            model_name='driverreshuffle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Створено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='earnings',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='schema',
            name='cash',
            field=models.IntegerField(default=500, verbose_name='Готівка водія'),
        ),
    ]
