# Generated by Django 4.1 on 2024-02-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_driverefficiencypolymorphic_total_orders_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle', verbose_name='Автомобіль'),
        ),
        migrations.AddField(
            model_name='fleetorder',
            name='date_order',
            field=models.DateField(null=True, verbose_name='Дата замовлення'),
        ),
        migrations.AddField(
            model_name='vehiclespending',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='cash',
            field=models.IntegerField(default=500, verbose_name='Контроль готівки водія з, грн'),
        ),
    ]
