# Generated by Django 4.1 on 2024-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_vehiclegps_app_vehicle_raw_dat_54650d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rawgps',
            index=models.Index(fields=['created_at'], name='app_rawgps_created_a3530a_idx'),
        ),
    ]
