# Generated by Django 4.1 on 2024-02-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0084_alter_fleetorder_date_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Назва категорії')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='penaltybonus',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle', verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='penaltybonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сума'),
        ),
        migrations.CreateModel(
            name='BonusCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.category')),
            ],
            options={
                'verbose_name': 'Категорія бонусу',
                'verbose_name_plural': 'Категорії бонусів',
            },
            bases=('app.category',),
        ),
        migrations.CreateModel(
            name='PenaltyCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.category')),
            ],
            options={
                'verbose_name': 'Категорія штрафу',
                'verbose_name_plural': 'Категорії штрафів',
            },
            bases=('app.category',),
        ),
        migrations.AddField(
            model_name='penaltybonus',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категорія'),
        ),
    ]
