# Generated by Django 4.1 on 2024-02-19 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_category_remove_bonus_vehicle_penaltybonus_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedVehicle',
            fields=[
            ],
            options={
                'verbose_name': 'Видалений автомобіль',
                'verbose_name_plural': 'Видалені автомобілі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.vehicle',),
        ),
        migrations.AddField(
            model_name='penaltybonus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Створено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penaltybonus',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='penalty_bonus/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='schema',
            field=models.CharField(choices=[('RENT', 'Схема оренди'), ('HALF', 'Схема 50/50'), ('DYNAMIC', 'Динамічна схема'), ('CUSTOM', 'Індивідуальний відсоток'), ('FLOAT', 'Плаваючий відсоток')], default=('HALF', 'Схема 50/50'), max_length=25, verbose_name='Шаблон схеми'),
        ),
    ]
