# Generated by Django 4.1 on 2024-02-29 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_deletedvehicle_penaltybonus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cash_control',
            field=models.BooleanField(default=True, verbose_name='Контроль готівки'),
        ),
        migrations.AddField(
            model_name='driver',
            name='cash_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0, message='Число повинно бути не менше 0.00'), django.core.validators.MaxValueValidator(1, message='Число повинно бути не більше 1.00')], verbose_name='Дозволено готівки'),
        ),
        migrations.AddField(
            model_name='driverpayments',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Відсоток водія'),
        ),
        migrations.AlterField(
            model_name='fleetsdriversvehiclesrate',
            name='pay_cash',
            field=models.BooleanField(default=True, verbose_name='Оплата готівкою'),
        ),
    ]
