# Generated by Django 4.1 on 2024-03-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_driverefficiencypolymorphic_total_orders_accepted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'partner')},
        ),
    ]
