# Generated by Django 4.1 on 2024-03-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.category')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.category',),
        ),
        migrations.RemoveField(
            model_name='vehiclespending',
            name='category',
        ),
        migrations.AddField(
            model_name='carefficiency',
            name='total_brand_trips',
            field=models.IntegerField(default=0, verbose_name='Всього поїздок бренду'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='branding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fleet', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='vehiclespending',
            name='spending_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.spendingcategory', verbose_name='Категорія'),
        ),
    ]
