# Generated by Django 4.1 on 2024-03-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_spendingcategory_remove_vehiclespending_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverreshuffle',
            name='dtp_or_maintenance',
            field=models.CharField(choices=[('accident', 'ДТП'), ('maintenance', 'Тех.Обслуговування')], max_length=100, null=True, verbose_name='Тип події'),
        ),
    ]
