# Generated by Django 4.1 on 2024-04-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0092_carefficiency_investor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayments',
            name='bolt_screen',
            field=models.ImageField(blank=True, null=True, upload_to='bolt', verbose_name='Фото звіту Bolt'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='status',
            field=models.CharField(
                choices=[('incorrect', 'Потребує поправок'), ('checking', 'Перевіряється'), ('pending', 'Очікується'),
                         ('completed', 'Виплачений'), ('failed', 'Не сплачений')], default='checking', max_length=20),
        ),
    ]
