# Generated by Django 4.1 on 2024-05-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_fleetorder_fleet_distance_investor_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.IntegerField(unique=True, verbose_name='ID транзакції')),
                ('start_time', models.DateTimeField(verbose_name='Початок зарядки')),
                ('end_time', models.DateTimeField(verbose_name='Кінець зарядки')),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ціна')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver', verbose_name='Водій')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle', verbose_name='Авто')),
            ],
        ),
        migrations.AddField(
            model_name='penalty',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.chargetransactions'),
        ),
    ]
